In [98]:
import tensorflow as tf
import numpy as np
import pandas

In [99]:
print ("Complete")

Complete


In [101]:
from __future__ import absolute_import 
from __future__ import division
from __future__ import print_function
from keras.callbacks import TensorBoard

In [102]:
rank_0_variable_1 = tf.Variable("Lion", tf.string)

In [103]:
print ( rank_0_variable_1 )

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'Lion'>


In [104]:
rank_0_int_variable_2 = tf.Variable(400, tf.int16)

In [105]:
print ( rank_0_int_variable_2 )

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=400>


In [106]:
rank_0_floating_variable_3 = tf.Variable(3.147, tf.float64)

In [107]:
print ( rank_0_floating_variable_3 )

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.147>


In [108]:
complex_variable_4 = tf.Variable(12.3-4.2j, tf.complex64)

In [109]:
print ( complex_variable_4 )

<tf.Variable 'Variable:0' shape=() dtype=complex128, numpy=(12.3-4.2j)>


In [110]:
ex_1_rank_1 = tf.Variable(["Hello"], tf.string)

In [111]:
print ( ex_1_rank_1 )

<tf.Variable 'Variable:0' shape=(1,) dtype=string, numpy=array([b'Hello'], dtype=object)>


In [112]:
ex_2_rank_1 = tf.Variable([13.14, 2.14], tf.float32)

In [113]:
print ( ex_2_rank_1 )

<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([13.14,  2.14], dtype=float32)>


In [114]:
complex_tensor_rank_1 = tf.Variable([12.3-4.8j, 7.5-1.5j], tf.complex64)

In [115]:
print (complex_tensor_rank_1)

<tf.Variable 'Variable:0' shape=(2,) dtype=complex128, numpy=array([12.3-4.8j,  7.5-1.5j])>


In [116]:
ex1_rank2 = tf.Variable([7], [11], tf.int16)

In [117]:
print(ex1_rank2)

<tf.Variable 'Variable:0' shape=(1,) dtype=int32, numpy=array([7], dtype=int32)>


In [118]:
image = tf.zeros([10, 200, 300, 3])

In [119]:
print(image)

tf.Tensor(
[[[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  ...

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]


 [[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  ...

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
 

In [120]:
ex1_reshape= tf.ones([3,4,5])

In [121]:
matrix= tf.reshape(ex1_reshape, [6, 10])
print(matrix)
print(ex1_reshape)

tf.Tensor(
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]], shape=(6, 10), dtype=float32)
tf.Tensor(
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]], shape=(3, 4, 5), dtype=float32)


In [122]:
matrix_B = tf.reshape(matrix, [3, -1])
print(matrix_B)

tf.Tensor(
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]], shape=(3, 20), dtype=float32)


In [123]:
matrix_Alt = tf.reshape(matrix_B, [4, 3, -1])
print(matrix_Alt)

tf.Tensor(
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]], shape=(4, 3, 5), dtype=float32)


In [124]:
# matrix_error = tf.reshape(matrix_Alt, [13, 2, -1])
# print(matrix_error)

In [129]:
# For version 1
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
x=tf.placeholder(tf.float32,shape=(1024,1024),name="X_float")
print(x)

Tensor("X_float_1:0", shape=(1024, 1024), dtype=float32)


In [126]:
print(tf.__version__)

2.0.0


In [135]:
# Same For version 2

x=tf.keras.Input(shape=(1024, 1024), name="X_float", dtype=tf.dtypes.float32)
print(x)

Tensor("X_float_3:0", shape=(?, 1024, 1024), dtype=float32)


In [136]:
y=tf.constant(1,dtype=tf.int32,shape=[24,1024],name="Alpha")
print(y)

Tensor("Alpha:0", shape=(24, 1024), dtype=int32)
